### ISSUE TITLE
Documentation not sufficient

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-tools-commander#100]
If I were a new user and I would want to row level secure my table using the commander, I would not know where to look. Of course I'm a pro and I know I have to type:
```
mcmd enable rls table
```
But with ```mcmd -h``` I would not know where to look. Maybe we can make a more verbose version of the help somehow.

**Comment by tommydeboer** [comment]
I think the top-level commands could list their subcommands automatically. Something like this:

```
add                 Add resources
                    (Sub-commands: users, group, token, theme, logo)
enable              Enable resources or functionality
                    (Sub-commands: rls, theme)

```

**Comment by marikaris** [comment]
Seems good to me!

**Comment by tommydeboer** [comment]
See https://stackoverflow.com/questions/20094215/argparse-subparser-monolithic-help-output
