### ISSUE TITLE
As user i could like to view and change the server to which i am connected

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-tools-commander#104]
As user i could like to view and change the server to which i am connected

- i do not know how to change/view the server 
- the --help option does not any info on this subject 
- the readme.md does not any info on this subject

**Comment by tommydeboer** [comment]
@connoratrug Changing the server can be done with `mcmd config set/add host`.

The problem with the help right now is that it's hard to see what sub-commands the toplevel commands have, see #100 .

A short 'Getting started' tutorial might be nice as well, I'll add a story for it.
