### ISSUE TITLE
Documentation on getting started and explanation of basic concepts

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-tools-commander#105]
Some documentation should be added on the basic concepts:
- location of properties file, scripts folder etc.
- datasets/resource folders
- scripts
- more?

**Comment by dtroelofsprins** [comment]
Perhaps it's already included in the description:
Documentation (plus small example) on how to configure (without editing) the mcmd.yaml from command line, but also on what the different sections (paths/resources) mean;

**Comment by tommydeboer** [comment]
See https://github.com/molgenis/molgenis-tools-commander/wiki/Getting-started
