### ISSUE TITLE
When importing a file into a package with dashes the import failes

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis-tools-commander#106]
## How to reproduce:
- mcmd add group emx-downloader
- mcmd import --in emx-downloader TypeTest.xlsx (in the testplan data)

## Expected behavoir
Imports ze file.

## Observed behavoir
Failes with 400

**Comment by tommydeboer** [comment]
Took a look with Sido and as it turns out the package identifier was actually `emx_downloader`. It's a bit confusing that a group named `emx-downlaoder` produces a package with an underscore but that's how it works.
