### ISSUE TITLE
Progress counter and ETA wanted for big imports

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis-tools-commander#111]
When importing a "big" EMX/TSV file, I have no way of knowing if and how it is progressing. For example, an import of 26k records has been running for ~15 minutes now and I don't know if 25900 inserts have been completed or 25.

Would be great to have an update counter (25900/26000 inserts done), preferably with an ETA based on the insert speed and records still left.

**Comment by tommydeboer** [comment]
This would be great, but sadly this information is not available in MOLGENIS. This feature has been requested before and will be implemented as part of the Import 2.0 rewrite. When that time has come I will reopen this issue.
