### ISSUE TITLE
As datamanager I would like to see which invalid config options I configured

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-tools-commander#121]
### How to Reproduce
Add this to your mcmd.yaml:
```yaml
test:
  - blaat
```
Run
```
mcmd
```
### Expected behavior
I get a warning because my options don't exist

### Observed behavior
The options I configured which are invalid are ignored

**Comment by tommydeboer** [comment]
This is intended behaviour because some properties may disappear between versions (some already have). The config shouldn't break in that case, or spew annoying warnings.
