### ISSUE TITLE
Allow override of add/update mode

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis-tools-commander#183]
Instead of 1 global config in the YAML file, allow overrides per command. For instance, say the overall preference is

`import_action: add`

which blocks the import of a custom 'home' for sys_StaticContent:

```
✖ Importing sys_StaticContent.tsv
  Value 'home' for unique attribute 'key_' from entity 'sys_StaticContent' already exists.
```
instead of changing everything to

`import_action: add_update_existing`

I want to say

`mcmd import -p sys_StaticContent.tsv -i add_update_existing`

for just this one import action.

**Comment by tommydeboer** [comment]
@joerivandervelde Great suggestion! This feature was introduced in [version 1.9.0](https://github.com/molgenis/molgenis-tools-commander/releases/tag/v1.9.0) 😄
