### ISSUE TITLE
Tests throw warnings because of a bug in Halo

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-tools-commander#53]
Halo throws warnings during the tests. 

It's being worked on: https://github.com/manrajgrover/halo/issues/97 & https://github.com/manrajgrover/halo/pull/107. Upgrade the Halo dependency as soon as that PR is merged.

**Comment by manrajgrover** [comment]
@tommydeboer This is being worked upon and will soon be fixed. :)

**Comment by tommydeboer** [comment]
@manrajgrover Great to hear! :)
