### ISSUE TITLE
mcmd gives login error

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-tools-commander#86]
When importing data, mcmd give following error:

<img width="823" alt="error_import_mcmd" src="https://user-images.githubusercontent.com/40240913/53402296-c21a2a00-39b1-11e9-81ef-59d6aa1986cd.png">

This is login error.
In yaml, token is not refreshed.

Work-around: remove token, save yaml.
Run mcmd import, works

**Comment by tommydeboer** [comment]
I did some research and it turns out the import endpoints return the (html) login page when authentication failed.
