### ISSUE TITLE
When my token is invalid and i login my give and delete fail

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-tools-commander#96]
# How to reproduce
1. Prepare using the following commands:
```
mcmd import it_emx_datatypes
mcmd add user test
mcmd give anonymous read sys_md
```
2. Demolish your token in de mcmd config
3. 
![54530570-6ffe7000-4983-11e9-9c6b-e2f99c01bcfe](https://user-images.githubusercontent.com/10075439/54754790-abe44000-4be4-11e9-8158-02d63421ed0f.png)
![Screen Shot 2019-03-21 at 14 22 33](https://user-images.githubusercontent.com/10075439/54754853-d504d080-4be4-11e9-87e4-937e54979eb0.png)

**Comment by tommydeboer** [comment]
From PR #90 :
>Turns out this problem is caused by having the anonymous user have read permission on sys_md_EntityType (and other system entities).

>When a query with an invalid token is done to check if the entity type exists, MOLGENIS handles the request like no token was present (see issue molgenis/molgenis#8241), thus defaulting back to the anonymous user's permissions. In this case, the anonymous user may query sys_md_EntityType but doesn't have read permissions on the actual row it_emx_datatypes_TypeTest.

>Can't do much about it until molgenis/molgenis#8241 is fixed I'm afraid.

In retrospect there is something we could do, suggested by @bartcharbon :
Do a separate request every time a command is executed to the `sys_sec_Token` entity to see if the token is still valid. This is table that should never be accessible to anonymous users.
