### ISSUE TITLE
Import data fails

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis-tools-commander#97]
MCMD trying to upload data to: https://ibd-private.test.molgenis.org/

When using mcmd importing of files fails. Error:
![error_importing](https://user-images.githubusercontent.com/40240913/54925856-76569400-4f0f-11e9-847e-b124a414ea89.png)

What I tried:
-using other rancher instance, importing others files work perfectly
-setting up new rancher for error import, result same error
-import with uploader import works

Data used for upload:
[IBD_1.xlsx](https://github.com/molgenis/molgenis-tools-commander/files/3003645/IBD_1.xlsx)

**Comment by marikaris** [comment]
This is probably not related to the commander, but a server related issue.
