### ISSUE TITLE
Version endpoint should also work with -v

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-tools-commander#99]
Type 
```
mcmd -v 
```

Expected: same output as --version

**Comment by tommydeboer** [comment]
Should already be a thing :) See #83

**Comment by marikaris** [comment]
I only checked -v, my bad. --version works

**Comment by tommydeboer** [comment]
-v is already used for verbosity

**Comment by marikaris** [comment]
Ah and because that flag is available in several parts of the tool, it cannot be used here. Ok, I get it.
